name: Update docker image in ACR

on:
  push:
    branches:
      - main
    tags: [ "v*.*.*" ]
    
env:
  IMAGE_NAME: espo2redrose
  
jobs:
  build:
    name: Build and push container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log into registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          version=${GITHUB_REF#refs/tags/}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest